# Generated by Django 3.2.9 on 2021-12-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
