# Generated by Django 3.2.9 on 2021-12-20 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vacancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancia',
            name='data_avaliacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vacancia',
            name='data_solicitacao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancia',
            name='situacao',
            field=models.CharField(max_length=255, null=False),
        ),
    ]
