# Generated by Django 3.2.9 on 2021-12-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211220_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancia',
            name='data_avaliacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancia',
            name='data_solicitacao',
            field=models.DateTimeField(),
        ),
    ]
