# Generated by Django 3.2.9 on 2021-12-22 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211220_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default='2021-12-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matricula',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True, verbose_name='Matrícula'),
            preserve_default=False,
        ),
    ]
