# Generated by Django 3.2.9 on 2021-12-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211222_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancia',
            name='observacao',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
